name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Jenkins
      uses: DylanK46/TeamEngima-ProjectEco-Webserver@master
      with:
        url: 'http://kainth.tk:49171/job/ProjectEco/build'
        method: 'POST'
        username: ${{ secrets.jenkins_user }}
        password: ${{ secrets.jenkins_token }}
